export const menu = [
  { id: 1, name: "House Special", price: 10.5, category: "Banh Mi" },
  { id: 2, name: "Pork Meatball", price: 9.75, category: "Banh Mi" },
  { id: 3, name: "Pork & Kimchi", price: 11.25, category: "Banh Mi" },
  { id: 4, name: "Pork Roll", price: 9.75, category: "Banh Mi" },
  { id: 5, name: "BBQ Pork", price: 9.75, category: "Banh Mi" },
  { id: 6, name: "Grilled Chicken", price: 9.75, category: "Banh Mi" },
  { id: 7, name: "Grilled Beef", price: 10.5, category: "Banh Mi" },
  { id: 8, name: "Grilled Pork", price: 9.75, category: "Banh Mi" },
  { id: 9, name: "Vegetarian", price: 9.75, category: "Banh Mi" },
  { id: 10, name: "Egg", price: 9.75, category: "Banh Mi" },
  { id: 11, name: "Pork Sausage", price: 9.75, category: "Banh Mi" },

  { id: 12, name: "Wonton Egg Noodle Soup", price: 18.5, category: "Soups / Wontons / Noodles" },
  { id: 13, name: "Wonton Soup", price: 12.5, category: "Soups / Wontons / Noodles" },
  { id: 14, name: "Chili Oil Wontons", price: 12.5, category: "Soups / Wontons / Noodles" },
  { id: 15, name: "Sweet & Tangy Wontons", price: 12.5, category: "Soups / Wontons / Noodles" },
  { id: 16, name: "Sweet Chili Ray Wontons", price: 13.5, category: "Soups / Wontons / Noodles" },
  { id: 17, name: "Stir-Fry Noodles", price: 18.5, category: "Soups / Wontons / Noodles" },
  { id: 18, name: "Organic Chicken Pho", price: 18.95, category: "Soups / Wontons / Noodles" },
  { id: 19, name: "Khao Soi Rice Noodle Soup", price: 18.95, category: "Soups / Wontons / Noodles" },
  { id: 20, name: "Thai Curry Chicken w/ Bread", price: 14.5, category: "Soups / Wontons / Noodles" },
  { id: 21, name: "Meatball Soup w/ Bread", price: 14.5, category: "Soups / Wontons / Noodles" },
  { id: 22, name: "Egg Drop Soup", price: 8.5, category: "Soups / Wontons / Noodles" },
];